# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01d2607941a02b634f616ab8a0aad14eca3883fd2ae6a357852275b03b177962f8be52536ff41dc3db7da1b6f2ec081665feb2cde749359e84dd2bfc09c6d897

test:
  secret_key_base: cf5288afdff5554b56dc01ae6af4ec9a1af2b2656f19a0aba4c44dd1f9fdee04f44e4d4304e8a91f91fa969822dc4e3099907508b1b50708aa3365727a4d0c8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
